name: grow
description: "AI x 自然栽培 - 栽培記録アプリ"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.2
  path: ^1.9.1
  uuid: ^4.5.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  geolocator: ^13.0.2
  google_mlkit_image_labeling: ^0.14.0
  http: ^1.2.2
  shared_preferences: ^2.3.4
  flutter_markdown: ^0.7.6
  native_exif: ^0.7.0
  url_launcher: ^6.2.5
  speech_to_text: ^7.0.0
  gal: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
